"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const vm = require("node:vm");

const editor = fs.readFileSync("web/project-editor.html", "utf8");
const quickRetouch = fs.readFileSync("web/project/quick-retouch.js", "utf8");
const quickRetouchCore = fs.readFileSync("web/project/quick-retouch-core.js", "utf8");
const quickRetouchCss = fs.readFileSync("web/project/quick-retouch.css", "utf8");
const projectApi = fs.readFileSync("web/project/forge-project-api.js", "utf8");
const projectBridge = fs.readFileSync("javascript/speech_bubble_project_bridge.js", "utf8");
const projectSchema = fs.readFileSync("speech_bubble_forge/project_schema.py", "utf8");
const projectStore = fs.readFileSync("speech_bubble_forge/project_store.py", "utf8");

new vm.Script(quickRetouch, { filename: "quick-retouch.js" });
new vm.Script(quickRetouchCore, { filename: "quick-retouch-core.js" });

assert.match(editor, /quick-retouch\.css/);
assert.match(editor, /quick-retouch-core\.js/);
assert.match(editor, /quick-retouch\.js/);
assert.match(editor, /quick-retouch-074-pan-cursor-1/);
assert.match(editor, /data-quick-retouch-open/);
assert.match(editor, /initializeQuickRetouch/);
assert.match(editor, /processLayerQuickRetouch/);
assert.match(editor, /role,"quick-retouch"|"quick-retouch",source/);
assert.match(editor, /metadata\?\.source === "quick-retouch"/);
assert.match(editor, /fit:source\?"cover":"contain"/);
assert.match(quickRetouch, /Selection active|選択範囲あり/);
assert.match(quickRetouch, /activeTool = "brush"/);
assert.match(quickRetouch, /activeTarget = \{ kind: "paint"/);
assert.match(quickRetouch, /data-retouch-original hidden/);
assert.match(quickRetouch, /data-retouch-panel="selection"/);
assert.match(quickRetouch, /data-retouch-panel="layers"/);
assert.match(quickRetouch, /data-retouch-panel="properties"/);
assert.match(quickRetouch, /mode: "brush-size"/);
assert.match(quickRetouch, /event\.button === 2/);
assert.match(quickRetouch, /event\.button === 1/);
assert.match(quickRetouch, /addEventListener\("wheel"/);
assert.match(quickRetouch, /selectionAction\("reselect"\)/);
assert.match(quickRetouch, /modifier && key === "a"/);
assert.match(quickRetouch, /modifier && key === "j"/);
assert.match(quickRetouch, /data\.cursorTool|dataset\.cursorTool/);
assert.match(quickRetouch, /Freehand Lasso|投げ縄選択/);
assert.match(quickRetouch, /selectionDisplay === "boundary"/);
assert.match(quickRetouch, /splitCompare/);
assert.match(quickRetouchCss, /quick-retouch-brush-ring/);
assert.match(quickRetouchCss, /quick-retouch-brush-ring\.resizing/);
assert.match(quickRetouchCss, /quick-retouch-brush-ring\.painting/);
assert.match(quickRetouchCss, /quick-retouch-brush-ring\.eraser/);
assert.match(quickRetouchCss, /eyedropper-temporary/);
assert.match(quickRetouchCss, /color-range-add/);
assert.match(quickRetouchCss, /color-range-exclude/);
assert.match(quickRetouch, /selectionOperationForModifiers/);
assert.match(quickRetouch, /colorSampleModeForModifiers/);
assert.match(quickRetouch, /brushRingFrame/);
assert.match(quickRetouch, /BUILD_VERSION = "0\.7\.4"/);
assert.match(quickRetouch, /dialog\.append\(brushRing\)/);
assert.match(quickRetouch, /let viewPanX = 0/);
assert.match(quickRetouch, /translate3d\(\$\{Math\.round\(viewPanX\)\}px/);
assert.match(quickRetouchCss, /data-cursor-tool="hand"/);
assert.match(quickRetouchCss, /data-cursor-tool="zoom"/);
assert.match(quickRetouchCss, /quick-retouch-floating-panel/);
assert.match(quickRetouch, /data-retouch-tool/);
assert.match(quickRetouch, /color_range/);
assert.match(quickRetouch, /hue_saturation/);
assert.match(quickRetouch, /brightness_contrast/);
assert.match(quickRetouch, /data-retouch-curve/);
assert.match(quickRetouch, /renderFullBlob/);
assert.match(quickRetouch, /Apply as New Page Image/);
assert.match(quickRetouchCore, /buildCurveLut/);
assert.match(quickRetouchCore, /floodSelect/);
assert.match(quickRetouchCore, /colorRangeMask/);
assert.match(quickRetouchCore, /renderStack/);
assert.match(quickRetouchCss, /dialog\.quick-retouch-dialog/);
assert.match(quickRetouchCss, /quick-retouch-floating-panel/);
assert.match(quickRetouch, /Freehand Lasso|投げ縄選択/);
assert.match(quickRetouch, /brush-size/);
assert.match(quickRetouch, /data-retouch-panel=\"selection\"/);
assert.match(projectApi, /`\$\{this\.base\}\/config`/);
assert.match(projectBridge, /searchParams\.set\("build", "0\.7\.4"\)/);
assert.match(projectSchema, /"retouched"/);
assert.match(projectStore, /"retouched"/);

console.log("quick_retouch_integration_test: OK");
